name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.6
          cache: pip
          architecture: x64

      - name: Install Dependencies
        run: 
          pip install -r requirements.txt

      - name: Build EXE
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: dict.py
          onefile: false
          standalone: true
          enable-plugins: pyside6
          disable-console: true
          
      - name: Copy Assets
        run:
          xcopy .\icon.png .\build\dict.dist\icon.png /y
          
      - name: Zip Build
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: build.win.standalone.zip
          path: ./build/dict.dist/
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build.win.standalone.zip
